### ISSUE TITLE
Dismissing window should deinitialise it

### ISSUE THREAD

**Issue by argie-w** [sunghyun-k/swiftui-window-overlay#1]
When dismissing the window it should be deinitialised and removed, however, this does not happen. When recalling the window later the .onAppear modifier does not execute.

**Comment by sunghyun-k** [comment]
Thank you for reporting this issue! I am already aware of it, and as a temporary workaround, you can use the following code:

```swift
if manager.isPresented {
  Color.clear
    .windowOverlay(isPresented: true) {
      ToastRootView(manager: manager)
    }
}
```

This should help in properly deinitializing and removing the window when dismissed. We're open to any suggestions or ideas for improvements if you have any.

**Comment by argie-w** [comment]
Thanks for the reply. Unfortunately, this doesn't really work for my use. Hopefully you can make the isPresented binding and deinitialise the window

**Comment by sunghyun-k** [comment]
https://github.com/sunghyun-k/swiftui-window-overlay/releases/tag/1.0.1

The latest release has resolved this issue. Thank you for feedback!
